# Generated by Django 5.1.2 on 2024-10-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.CharField(max_length=20, primary_key='cid', serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('loan', models.IntegerField()),
                ('years', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
